### ISSUE TITLE
tinymce plugin not running in Firefox

### ISSUE THREAD

**Issue by astronaut-wannabe** [mavoweb/plugins#12]
I am going to the grumpy cat demo with`?storage=local` to test this: http://mavo.io/demos/homepage/?storage=local

Browser: 53.0.3 (64-bit)
OS: MacOS Sierra 10.12.5 (16F73)

### firefox
<details>
<summary>expand for gif</summary>

![firefox](https://cloud.githubusercontent.com/assets/13190980/26500805/a2a90970-4237-11e7-8a26-e32c4e8df69b.gif)

</details>

### chrome
<details>
<summary>expand for chrome gif</summary>

![chrome](https://cloud.githubusercontent.com/assets/13190980/26500820/acd0efa8-4237-11e7-9f87-6e083e81fd52.gif)
</details>

**Comment by astronaut-wannabe** [comment]
This might be all plugins? Both `tinymce` and `markdown` only work in Safari and Chrome for me

**Comment by LeaVerou** [comment]
What was your previous version of Firefox?

**Comment by astronaut-wannabe** [comment]
`53.0.3` is the version I have where it is not working

I also have the firefox nightly installed (version `54.0a2`) and it works in that version

**Comment by LeaVerou** [comment]
That's bizarre. It works here on Firefox 53.0.3, also OSX Sierra (though 10.12.4)...
Perhaps it could be an extension?

**Comment by astronaut-wannabe** [comment]
@LeaVerou that was it!

Specifically, PrivacyBadger blocking `cdn.polyfill.io` is what was breaking it.

went ahead and submitted the issue via the PrivacyBadger app

<img width="433" alt="screen shot 2017-05-28 at 8 52 31 pm" src="https://cloud.githubusercontent.com/assets/13190980/26531362/da145854-43e7-11e7-9772-b769aa909a52.png">

**Comment by LeaVerou** [comment]
Glad to hear we found the source of the issue! I'm not sure `polyfill.io` is the problem here (Firefox 53 is modern enough to not break without polyfills), it looks much more likely that PrivacyBadger is also blocking cdnjs? Perhaps the list there is scrolleable and cdnjs is listed there? The domain is https://cdnjs.cloudflare.com

**Comment by astronaut-wannabe** [comment]
It is a scrollable list, but I don't see cloudflare in there. Here is a gif of what I did:

![grumpcat](https://cloud.githubusercontent.com/assets/13190980/26562477/d8004c6e-44c6-11e7-85e7-af46dd7ba11c.gif)

**Comment by LeaVerou** [comment]
Ah, I see tinymce has its own CDN, and it's not blocked. Oh well, since this is fixed now, I guess all is good. :)
