### ISSUE TITLE
Made a PHP backend

### ISSUE THREAD

**Issue by Falafel65** [mavoweb/plugins#14]
Hi,

I've made a PHP backend for Mavo (https://github.com/Falafel65/mavo-php), to work with local server.
Could it be reviewed and if it's ok, added to plugins list ?

**Comment by LeaVerou** [comment]
This is so exciting!! Thank you for making this!!! 

You can actually add it yourself, if you go to http://plugins.mavo.io/ , login to Github, add it, save, and click "Send edit suggestion" (which sends a pull request here). Make sure to fill in the "repo" field (value should be `Falafel65/mavo-php`), that's what tells the Plugin directory that this plugin is stored in a separate repo.

Are you interested in improving it? I have some feedback about the API :)

**Comment by Falafel65** [comment]
> Are you interested in improving it? I have some feedback about the API :)

Sure ! I wrote it while discovering Mavo, I've surely missed lot of things.

**Comment by LeaVerou** [comment]
My main comment is that it's a bit limiting that all three (app, json, PHP file) need to be in the same directory. Also, that the value of `mv-app` is used to determine the filename. And what if it's not JSON? What if it's CSV or Yaml or anything else?

I would suggest using `mv-storage` for a (potentially relative to the HTML document) filepath which is on par with how `mv-storage` is used in other places. However that begs the question: How will Mavo know then when to use the PHP storage backend? Sadly, there is no answer to that currently, but there will be soon, once I implement https://github.com/mavoweb/mavo/issues/240.

**Comment by Falafel65** [comment]
> My main comment is that it's a bit limiting that all three (app, json, PHP file) need to be in the same directory.

I started Mavo by  reading JSON file for my app (using mv-source, putting "file.json" explicitely), then I searched how to write to them. I was simpler then to have everything in the same place.
Still, I think that the PHP and the APP should be on the same directory, for ease of use. Or it'll need another `mv-` attribute to give the (relative ?) folder where the PHP is. It currently only  use `Mavo.base` to build the URL.

> Also, that the value of mv-app is used to determine the filename. And what if it's not JSON? What if it's CSV or Yaml or anything else?

For the moment, if it's anything else than JSON, it can't write it ;)
I can use the `mv-format`, but then the backend would have to know how to write to each file format given, some of them may not have PHP library to be manipulated. JSON, CSV or Text are well supported, but others ?

> I would suggest using mv-storage for a (potentially relative to the HTML document) filepath which is on par with how mv-storage is used in other places. However that begs the question: How will Mavo know then when to use the PHP storage backend? Sadly, there is no answer to that currently, but there will be soon, once I implement mavoweb/mavo#240.

I'll keep an eye on it !

**Comment by LeaVerou** [comment]
> Still, I think that the PHP and the APP should be on the same directory, for ease of use. Or it'll need another `mv-` attribute to give the (relative ?) folder where the PHP is. It currently only use `Mavo.base` to build the URL.

Yeah, I agree. But at least the data should be able to be anywhere, since we already have an attribute for its location :)

> For the moment, if it's anything else than JSON, it can't write it ;)
I can use the `mv-format`, but then the backend would have to know how to write to each file format given, some of them may not have PHP library to be manipulated. JSON, CSV or Text are well supported, but others ?

You don't have to deal with `mv-format` in your storage adapter, the data that is passed through your `put()` and `get()` methods is already decoded/encoded. 
Why does PHP need to manipulate them? All it needs is to write the file that Mavo sends it…

I understand that in your use case you may need to decode it on the server-side, but a generic PHP storage backend doesn't need that. All it needs is to write the file and do access control.
You can separate out the code that decodes it and only have it in your app. :)

> I'll keep an eye on it !

It's done! `mv-storage-type="php"` (it's case insensitive, so `PHP` works too)

**Comment by Falafel65** [comment]
>> I'll keep an eye on it !

> It's done! mv-storage-type="php" (it's case insensitive, so PHP works too)

Wow, things are going fast around here :D

> the data should be able to be anywhere

Agree ! I'll edit for this. The path is given using `mv-storage` ?

> the data that is passed through your put() and get() methods is already decoded/encoded.
Why does PHP need to manipulate them? All it needs is to write the file that Mavo sends it…

That's the point I'm not getting. I had data in object format sent, that I encoded through POST, sent to PHP, decoded and written to JSON. 
You are saying that I don't need to do all that, but what Mavo is sending to the adapter, really ? I'll need to dig into sources, I've not seen it :/

**Comment by LeaVerou** [comment]
> Agree ! I'll edit for this. The path is given using `mv-storage` ?

Yes (or `mv-source`, or `mv-init`...), but you don't have to worry about this, it's automatically in `this.url` (`this.source` contains the raw, unparsed value) as described here: https://mavo.io/docs/storage/#creating-your-own-storage-backend

> That's the point I'm not getting. I had data in object format sent, that I encoded through POST, sent to PHP, decoded and written to JSON.
You are saying that I don't need to do all that, but what Mavo is sending to the adapter, really ? I'll need to dig into sources, I've not seen it :/

`put()` receives data encoded as a string based on the current format. If that format is JSON (the default), it's a string that contains JSON. There is no point in decoding it and re-encoding it on the server. 

After looking at your code, it appears you are merging the data sent with the old data. This is unnecessary, as Mavo is sending **all data** back, not just a delta from the previous data.

**Comment by Falafel65** [comment]
>  it's automatically in this.url

In fact, Mavo is doing almost everything, I feel a little useless :D

> it's a string that contains JSON. There is no point in decoding it and re-encoding it on the server.

And I was inefficient. Mavo may end harming my self-esteem lol
Well ok, so it means basically that the adapter only need to handle authentication and saving to persistent storage.



> This is unnecessary, as Mavo is sending all data back, not just a delta from the previous data.

I was doing a sort of classic POST, and my usecase not all fields were present in my App (different properties by position in pages, same app ID).

Anyway, thanks for our time and explanations ! 😺

**Comment by LeaVerou** [comment]
> In fact, Mavo is doing almost everything, I feel a little useless :D
> And I was inefficient. Mavo may end harming my self-esteem lol

Hey, there is so little documentation on extending Mavo right now that I have great respect for anyone developing plugins before I document the API properly!

> Well ok, so it means basically that the adapter only need to handle authentication and saving to persistent storage.

Yup!

> I was doing a sort of classic POST, and my usecase not all fields were present in my App (different properties by position in pages, same app ID).

They don't have to be. If they're present in the data, they are preserved. :)

**Comment by Falafel65** [comment]
> Hey, there is so little documentation on extending Mavo right now that I have great respect for anyone developing plugins before I document the API properly!

There __is__ documentation, at least ! 😄 And source is clear and well commented !

Well I've got work to simplify everything, since Mavo is doing all the hard work !
Thanks for your answers, this part of the story is closed !
