### ISSUE TITLE
Latest changes not always saved with TinyMCE

### ISSUE THREAD

**Issue by RubenVerborgh** [mavoweb/plugins#17]
When editing a TinyMCE field and hitting save directly after (without “leaving” the TinyMCE field first in another way), sometimes the slightly older version of the field is saved instead of the latest contents.

**Comment by LeaVerou** [comment]
This is why: https://github.com/mavoweb/plugins/blob/master/tinymce/mavo-tinymce.js#L33
So it depends on when TinyMCE fires the `change` event. I don't think it has an `input` event, but perhaps we could throttle keystrokes or wait for a delay or something.

**Comment by RubenVerborgh** [comment]
On blur perhaps?

**Comment by LeaVerou** [comment]
> On blur perhaps?

That's the current situation.

**Comment by RubenVerborgh** [comment]
So it was not due to the type of event (change/blur) nor due to the timing of the event. Rather, `innerHTML` is not always in sync with `editor.getContent()`.

**Comment by LeaVerou** [comment]
`change` events are fired on blur, typically.
`innerHTML` is on sync with `editor.getContent`. `innerHTML` is not always in sync with the internal property value though, which is what is saved.

**Comment by RubenVerborgh** [comment]
> `change` events are fired on blur, typically.

Not with TinyMCE, it has [its own logic](https://www.tinymce.com/docs/advanced/events/#change).

> `innerHTML` is on sync with `editor.getContent`.

I found out with some testing that they're not, hence why #19 is needed / works. (I suspect that TinyMCE throttles updates to be more responsive.)
