### ISSUE TITLE
Markdown plugin preload content

### ISSUE THREAD

**Issue by jenil** [mavoweb/plugins#29]
What's the best way to prefill content in a `div` with markdown plugin on it?

Currently:
![image](https://user-images.githubusercontent.com/971411/36937553-24ab3e1a-1ee3-11e8-9d83-d876741a6faa.png)

![image](https://user-images.githubusercontent.com/971411/36937563-444caf88-1ee3-11e8-9d4c-37a0e940190c.png)

**Comment by LeaVerou** [comment]
Put the content in the div? Which you seem to already be doing, so I guess I’m misunderstanding the question...

**Comment by jenil** [comment]
Okay, let me explain it better —

I want to make content editable on the page.

Here is the HTML:

```html
<div class="content markdown" property="content" mv-multiple># Welcome 
    
Kick-off the repository for your amazing new design system new creating a new page from the left sidebar. Also, make sure you have the Sketch plugin installed so that you can import designs into the repository.
</div>
```

It produces:
```html
<div class="content markdown" property="content" mv-multiple="" mv-expressions="none" aria-label="Content" mv-attribute="none">
<h1 id="welcome-kick-off-the-repository-for-your-amazing-new-design-system-new-creating-a-new-page-from-the-left-sidebar-also-make-sure-you-have-the-sketch-plugin-installed-so-that-you-can-import-designs-into-the-repository">
Welcome Kick-off the repository for your amazing new design system new creating a new page from the left sidebar. Also, make sure you have the Sketch plugin installed so that you can import designs into the repository.
</h1>
</div>
```

Expected:
```html
<div class="content markdown" property="content" mv-multiple="" mv-expressions="none" aria-label="Content" mv-attribute="none">
<h1>Welcome!</h1>
<p>Kick-off the repository for your amazing new design system new creating a new page from the left sidebar.
<br> Also, make sure you have the Sketch plugin installed so that you can import designs into the repository.</p>
</div>
```

**Comment by LeaVerou** [comment]
Oh I see. Wow, what a weird bug. It might even be a Showdown bug (the library we use for parsing Markdown).

It would really help to put this online somewhere so I can take a look.
Which browser/version/OS does this happen in?

**Comment by jenil** [comment]
I did make a [codepen](https://codepen.io/jgog/pen/QQPxRQ) and it works totally fine. But I suspect **maybe** because this is in the browser and the newline character is parsed differently there.

Can you try this locally once?

**Comment by LeaVerou** [comment]
I did and I could not reproduce :(

But AFAIK browsers handle newlines the same across local and remote contexts.
Are you including some other script that may be interfering with newlines?

**Comment by jenil** [comment]
[Here is the source](https://github.com/jenil/docur/blob/e8abb249cdf522fbe89f6b587dfb283b5bcacf0d/index.html#L38) with a workaround at the moment. 

My setup:
Mac OS High Sierra
Google Chrome latest
VS Code with Prettifier for formatting

If that helps.

**Comment by jenil** [comment]
Demo: https://jenil.github.io/docur/

**Comment by LeaVerou** [comment]
I’m also running Chrome latest on High Sierra.

I wonder if VS Code is doing something with your newlines. If you View Source on the page you linked there are no newlines in it:
![image](https://user-images.githubusercontent.com/175836/36939807-befb1f68-1f05-11e8-9743-5a072caae9e1.png)

**Comment by jenil** [comment]
ahhh damn! my bad, its the HTML minification that's causing it 🙈

Thanks for your help!

**Comment by LeaVerou** [comment]
Yay, glad we figured it out! 😀
