### ISSUE TITLE
[markdown] Automatic image upload when image is pasted

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/plugins#65]
This should be relatively easy as it's mainly reusing the code from image uploads that we support elsewhere, then getting the returned URL and inserting it in the MD. 

I suppose while the upload is pending you'd want to enter something like `![Uploading...]()` and disable the textarea. Github's comment area is a good example of good UI for this.

@DmitrySharabin would you be interested in implementing this, since you've worked with uploads before?

**Comment by DmitrySharabin** [comment]
I would love to give it a shot and try to implement this feature. Just a couple of thoughts/questions to clarify.

An image supposed to be inserted via dragging and dropping or copying and pasting it into a `<textarea>`, right? And the insertion point is the cursor position?

Should we also add an action button as Github does?
![image](https://user-images.githubusercontent.com/9166277/86539194-4dd78b00-bf03-11ea-9154-08802e4645a6.png)
And if Mavo authors won't want to provide such functionality (the action button) to end-users, they can easily hide it via CSS. Anything else?

**Comment by LeaVerou** [comment]
> I would love to give it a shot and try to implement this feature. 

Yay!

> An image supposed to be inserted via dragging and dropping or copying and pasting it into a <textarea>, right? 

Yes. I'd say pasting is more high priority, but d&d would be nice too.

> And the insertion point is the cursor position?

Yes.

> Should we also add an action button as Github does?

I'm not sure. We don't have action buttons for other things that we provide conveniences for in the Markdown textarea (bold, italic, links etc). OTOH it's a pretty cool feature to be hidden. Maybe as a default placeholder? I'll think about it.

Anyhow, let's focus on the basic functionality now, and we can focus on making it more visible later.

**Comment by DmitrySharabin** [comment]
Can we close it since we already merged the corresponding PR?

**Comment by LeaVerou** [comment]
Sure! Thanks again!
