### ISSUE TITLE
TinyMCE plugin needs to be updated to version 5 before 25 february 2021

### ISSUE THREAD

**Issue by EtunaAikido** [mavoweb/plugins#73]
I get this warning in my console when using mv-plugins="tinymce".

"The CDN you are currently using to access TinyMCE will be turned off on 25 Februrary 2021. Please ensure you upgrade TinyMCE (https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/) in order to not lose access to the editor."

Mavo is currently using https://cdn.tinymce.com/4/tinymce.min.js, which according to the blogpost indeed will be shut down on February 25th 2021. The new version seems to require an api-key and a "tiny.cloud" account for some reason, so it might not be compatible with how Mavo loads the plugin right now? (if it has to be a personal api-key and not a global one), but there may be alternatives.

**Comment by LeaVerou** [comment]
Oof. Pinging @karger and @DmitrySharabin.

**Comment by LeaVerou** [comment]
Thank you for the report @EtunaAikido!

**Comment by DmitrySharabin** [comment]
I wonder if we'll host the corresponding JS and CSS files of the library on the Mavo site to let the plugin work? Will it solve the issue? Or is it illegal?

**Comment by LeaVerou** [comment]
I have no idea, but I'm fine with that! Fewer DNS lookups would also make it faster!

**Comment by DmitrySharabin** [comment]
The issue is fixed.
