### ISSUE TITLE
TinyMCE plugin: ability to pass options via attributes

### ISSUE THREAD

**Issue by tscanlin** [mavoweb/plugins#81]
Hello, I really like Mavo and all of the functionality it provides, thanks for creating / maintaining it and sharing it with the world!

I was wondering if you would be open to a PR to add the ability to pass options to configure TinyMCE via DOM attributes. For my use case I'd like to configure the `toolbar`. Would you be open to this?

**Comment by LeaVerou** [comment]
Sure!

**Comment by DmitrySharabin** [comment]
I believe we can close it.
