### ISSUE TITLE
getting 404 of my hebrew locale 

### ISSUE THREAD

**Issue by seffyfisher** [mavoweb/plugins#93]
just got back to play with mavo and i found out the langugaes plugins didnt work for me if im using the mv-plugins attribute in the mvapp
for instance ive included :
mv-plugins="locale-he"
and then im getting 404 :
ive checked the url:
the url it try to get:https://cdn.jsdelivr.net/gh/seffyfisher/mavo-locale-he/@master/mavo-locale-he.js
the correct url: https://cdn.jsdelivr.net/gh/seffyfisher/mavo-locale-he@master/mavo-locale-he.js
the diffrence between them is the "/@" instead of no slash

ive checked the greek locale via mv-plugins="locale-el" and it works well
so i guess its something to do with the link of my github account
i just wanted to fix it and i wasn't sure how and if the problem is at my end and how to fix it

p.s.
i would love to keep contribute to the project let me know what is needed now so maybe i can try to help

**Comment by DmitrySharabin** [comment]
Hey @seffyfisher! 👋🏻

Thank you for reporting this issue. It was the trailing slash in the repo address.

<img width="587" alt="Screen Shot 2021-06-04 at 17 15 34" src="https://user-images.githubusercontent.com/9166277/120815602-a7539a00-c558-11eb-8023-2c896c659115.png">

Now it should be fixed. Will you please take a look?

**Comment by seffyfisher** [comment]
it works! thank you so much for fixing it so quickly
i highly appreciate it.
i saw your projects with mavo, really great stuff!
let me know what is needed so i can help as well.
thanks again.
