### ISSUE TITLE
Autoload plugins

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/plugins#95]
I've experimented with this idea in [inspire.js](https://github.com/LeaVerou/inspire.js/blob/master/inspire.js#L33) and I think it works really well. 
There's a registry of plugin ids and selectors. If a selector matches, the corresponding plugin is autoloaded.

In inspire.js this is default functionality, but in Mavo we could develop it as a plugin. Then people only need to specify `mv-plugins="autoload"` and add/remove plugins by simply using them.

Plugins could declare what selector applies to them via an extra field in the registry.

**Comment by joyously** [comment]
I think that sounds good until there are naming clashes.

**Comment by LeaVerou** [comment]
Could you elaborate?

**Comment by DmitrySharabin** [comment]
[The requested plugin](https://plugins.mavo.io/plugin/autoload) is live! 🥳
